- name: Start container
  community.docker.docker_container:
    name: dozzle
    image: "{{ dozzle_image }}:{{ dozzle_version }}"
    networks:
      - name: traefik-public
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080"
    env:
      DOZZLE_ENABLE_ACTIONS: "true"
    labels:
      traefik.enable: "true"
      traefik.http.routers.dozzle.entrypoints: websecure
      traefik.http.routers.dozzle.rule: Host(`{{ dozzle_domain }}`)
      traefik.http.routers.dozzle.tls: "true"
      traefik.http.services.dozzle.loadbalancer.server.port: "{{ dozzle_port }}"
