---
- name: Redis Insight
  become: true
  community.general.flatpak:
    name: com.redis.RedisInsight
    state: present

- name: Redis TUI | Get Latest Release
  community.general.github_release:
    action: latest_release
    user: davidbudnick
    repo: redis-tui
    token: "{{ github_token }}"
  register: redis_release

- name: Redis TUI | Download Binary
  ansible.builtin.unarchive:
    src: https://github.com/davidbudnick/redis-tui/releases/download/{{ redis_release.tag }}/redis-tui_{{ redis_release.tag[1:] }}_Linux_x86_64.tar.gz
    dest: "{{ setup_dir }}"
    remote_src: true
  become: true

- name: Redis TUI | Install Binary
  ansible.builtin.copy:
    src: "{{ setup_dir }}/redis-tui"
    dest: "{{ bin_dir }}/redis-tui"
    mode: a+x
  become: true
