- ansible.builtin.import_tasks: libvirt.yml
  tags: ["libvirt"]
- ansible.builtin.import_tasks: virtualbox.yml
  tags: ["virtualbox"]
- ansible.builtin.import_tasks: gnome-boxes.yml
  tags: ["gnome-boxes"]
