- name: Flatpak | Install
  ansible.builtin.dnf:
    name: "flatpak"
    state: present
  become: true
- name: Flatpak | Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true
- name: Flatpak | Install Flatseal app
  community.general.flatpak:
    name: com.github.tchx84.Flatseal
    state: present
  become: true
