- name: Nautilus | Set preferences
  community.general.dconf:
    key: '{{ item.key }}'
    state: present
    value: '{{ item.value }}'
  with_items:
    - key: /org/gnome/nautilus/preferences/default-folder-viewer
      value: '''icon-view'''
    - key: /org/gnome/nautilus/preferences/show-hidden-files
      value: 'true'
    - key: /org/gnome/nautilus/preferences/recursive-search
      value: '''never'''
