---
- name: Download installer
  ansible.builtin.get_url:
    url: https://radicle.xyz/install
    dest: /tmp/radicle-install.sh
    mode: "0755"

- name: Install
  ansible.builtin.command:
    argv:
      - sh
      - /tmp/radicle-install.sh
  changed_when: true
