- name: Ansible playbook to setup my local machine
  hosts: all
  vars_files:
    - vars/main.yml
  vars_prompt:
    - name: github_token
      prompt: "What is your GitHub Token?"
      default: "{{ lookup('env','GITHUB_TOKEN') }}"
      private: true
  pre_tasks:
    - name: Ensure setup directory exists
      ansible.builtin.file:
        path: "{{ setup_dir }}"
        state: directory
        mode: "0755"
      tags: [always]
  post_tasks:
    - name: Remove setup directory
      ansible.builtin.file:
        path: "{{ setup_dir }}"
        state: absent
      become: true
      tags: [always]
  handlers:
    - name: restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
      become: true
  tasks:
    - ansible.builtin.import_tasks: tasks/system/_main.yml
      tags: ["system"]
    - ansible.builtin.import_tasks: tasks/dotfiles.yml
      tags: ["dotfiles"]
    - ansible.builtin.import_tasks: tasks/shell/_main.yml
      tags: ["shell"]
    - ansible.builtin.import_tasks: tasks/cli/_main.yml
      tags: ["cli"]
    - ansible.builtin.import_tasks: tasks/internet/_main.yml
      tags: ["internet"]
    - ansible.builtin.import_tasks: tasks/productivity/_main.yml
      tags: ["productivity"]
    - ansible.builtin.import_tasks: tasks/utilities/_main.yml
      tags: ["utilities"]
    - ansible.builtin.import_tasks: tasks/multimedia/_main.yml
      tags: ["multimedia"]
    - ansible.builtin.import_tasks: tasks/dev/_main.yml
      tags: ["dev"]
    - ansible.builtin.import_tasks: tasks/games/_main.yml
      tags: ["games"]
    - ansible.builtin.import_tasks: tasks/network/_main.yml
      tags: ["networking"]
    - ansible.builtin.import_tasks: tasks/desktop/_main.yml
      tags: ["desktop"]
    - ansible.builtin.import_tasks: tasks/virtualization/_main.yml
      tags: ["virtualization"]
    - ansible.builtin.import_tasks: tasks/docker-apps/_main.yml
      tags: ["docker-apps"]
