- name: Update System
  hosts: all
  tasks:
    - name: Update system installed packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true
        update_cache: true
      become: true
    - name: Update flatpak installed packages
      ansible.builtin.command: flatpak update -y
