---
- name: Load distribution-specific vars
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Install
  ansible.builtin.package:
    name: "{{ golang_package }}"
    state: present
  become: true

- name: Include golangci-lint tasks
  ansible.builtin.include_tasks: golangci-lint.yml
