---
- name: Get latest release
  community.general.github_release:
    action: latest_release
    repo: lazydocker
    token: "{{ github_token }}"
    user: jesseduffield
  register: lazydocker_release

- name: Download
  ansible.builtin.unarchive:
    dest: "{{ setup_dir }}"
    remote_src: true
    src: https://github.com/jesseduffield/lazydocker/releases/download/{{ lazydocker_release.tag }}/lazydocker_{{ lazydocker_release.tag[1:] }}_Linux_x86_64.tar.gz
  become: true

- name: Install
  ansible.builtin.copy:
    dest: "{{ bin_dir }}/lazydocker"
    mode: a+x
    src: "{{ setup_dir }}/lazydocker"
  become: true
