- name: Laod Distribution specific vars
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  failed_when: false

- name: Install
  ansible.builtin.package:
    name: "{{ chromium_package }}"
    state: present
  become: true

