- name: Get Latest Release
  community.general.github_release:
    action: latest_release
    user: openziti
    repo: zrok
    token: "{{ github_token }}"
  register: latest_release

- name: Download
  ansible.builtin.unarchive:
    src: "https://github.com/openziti/zrok/releases/download/{{ latest_release.tag }}/zrok_{{ latest_release.tag[1:] }}_linux_amd64.tar.gz"
    dest: "{{ setup_dir }}"
    remote_src: yes

- name: Install
  ansible.builtin.copy:
    src: "{{ setup_dir }}/zrok"
    dest: "{{ bin_dir }}"
    mode: "a+x"
  become: true
