---
- name: Get latest release version
  community.general.github_release:
    action: latest_release
    user: spotDL
    repo: spotify-downloader
    token: "{{ github_token }}"
  register: spotdl_release

- name: SpotDL | Download
  ansible.builtin.get_url:
    dest: "{{ bin_dir }}/spotdl"
    mode: a+x
    url: "https://github.com/spotDL/spotify-downloader/releases/download/{{ spotdl_release.tag }}/spotdl-{{ spotdl_release.tag[1:] }}-linux"
  become: true
