# Ansible Galaxy Roles
roles:
  - src: https://github.com/jaredhocutt/ansible-gnome-extensions

collections:
  - name: community.general
    version: 9.3.0

  - name: community.docker
    version: 3.12.1

  - name: ansible.posix
    version: 1.5.4


