version: "3"

tasks:
  default:
    cmds:
      - task -l

  dev:
    desc: Setup development environment
    cmds:
      - python3 -m venv .venv && source .venv/bin/activate
      - pip install -r requirements.txt
      - task galaxy

  galaxy:
    desc: Install Ansible Galaxy roles
    cmds:
      - ansible-galaxy install -p .ansible_galaxy/roles -r requirements.yml
      - ansible-galaxy collection install -p .ansible_galaxy/collections -r requirements.yml

  lint:
    desc: Runs Ansible Lint agains manifests
    cmds:
      - ansible-lint playbooks/setup.yml roles

  check:
    desc: Check syntax of playbooks
    cmds:
      - ansible-playbook --syntax-check playbooks/*.yml

  run:
    desc: Run main playbook
    cmds:
      - ansible-playbook --ask-become-pass

  run-i:
    desc: Run interactive playbook
    interactive: true
    silent: true
    cmds:
      - |
        ALL_PLAYBOOKS=$(ls playbooks/*.yml)
        PLAYBOOK=$(gum choose --header "Select playbook to run" ${ALL_PLAYBOOKS})
        TAG=$(gum input --header "Enter tag to run")

        ansible-playbook --ask-become-pass ${PLAYBOOK:-setup.yml} --tags ${TAG:-all}
