version: "3"

tasks:
  default:
    cmds:
      - task -l

  dev:
    desc: Setup development environment
    cmds:
      - python3 -m venv .venv && source .venv/bin/activate
      - pip install -r requirements.txt
      - task galaxy

  galaxy:
    desc: Install Ansible Galaxy roles
    cmds:
      - ansible-galaxy install -p .ansible_galaxy/roles -r requirements.yml
      - ansible-galaxy collection install -p .ansible_galaxy/collections -r requirements.yml

  lint:
    desc: Runs Ansible Lint agains manifests
    cmds:
      - ansible-lint playbooks roles inventories

  check:
    desc: Check syntax of a playbook against an inventory
    cmds:
      - ansible-playbook --syntax-check -i ${INVENTORY:?set INVENTORY} --limit ${LIMIT:-all} playbooks/${PLAYBOOK:-setup.yml}

  run:
    desc: Run interactive playbook
    interactive: true
    silent: true
    cmds:
      - |
        ALL_PLAYBOOKS=$(ls playbooks/*.yml)
        ALL_INVENTORIES=$(ls inventories/*/*.ini)
        ALL_HOSTS="tuxedo-laptop zenbook-laptop"
        PLAYBOOK=$(gum choose --header "Select playbook to run" ${ALL_PLAYBOOKS})
        INVENTORY=$(gum choose --header "Select inventory to run" ${ALL_INVENTORIES})
        LIMIT=$(gum choose --header "Select host to run" ${ALL_HOSTS})
        TAG=$(gum input --header "Enter tag to run")

        ansible-playbook -i ${INVENTORY} --limit ${LIMIT} --ask-become-pass ${PLAYBOOK:-playbooks/setup.yml} --tags ${TAG:-all}
