- name: Ulauncher
  ansible.builtin.dnf:
    name: ulauncher
    state: present
  become: true
- name: Install Ulauncher extension Python packages dependencies
  ansible.builtin.pip:
    name:
    - requests
    - memoization
    - dateparser
    - faker
    - semver
    - PyGithub~=1.57
    - cloudFlare~=2.11.0
    - algoliasearch~=2.6.0
    - docker
    - frontmatter
    - typing_extensions
    - python-raindropio
    - brotab~=1.3.0
    - jira
    - atlassian-python-api~=3.0
    - lorem
    - fuzzywuzzy
    - python-gitlab
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
