- name: Docker | Install Repo
  ansible.builtin.yum_repository:
    baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
    description: Docker
    gpgkey: https://download.docker.com/linux/fedora/gpg
    name: docker

- name: Docker | Install Packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  become: true

- name: Docker | Add current user to Docker group
  ansible.builtin.user:
    append: true
    groups: docker
    name: '{{ user }}'
  become: true

- name: Docker | Reload group
  ansible.builtin.command: newgrp docker
  become: true

- name: Docker | Copy Daemon.json
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    mode: '0644'
    src: daemon.json
  become: true

- name: Docker | Start service
  ansible.builtin.systemd:
    enabled: true
    name: docker
    state: started
