- name: Bitwarden | Get latest release version
  community.general.github_release:
    user: bitwarden
    repo: cli
    action: latest_release
    token: "{{ github_token }}"
  register: bw_release
- name: Bitwarden | Download
  ansible.builtin.unarchive:
    remote_src: true
    src: https://github.com/bitwarden/cli/releases/download/{{ bw_release.tag }}/bw-linux-{{ bw_release.tag[1:] }}.zip
    dest: "{{ bin_dir }}"
    mode: a+x
  become: true
