- name: YQ | Get latest release
  community.general.github_release:
    user: mikefarah
    repo: yq
    action: latest_release
    token: "{{ github_token }}"
  register: release
- name: YQ | Download and Install
  ansible.builtin.get_url:
    url: "https://github.com/mikefarah/yq/releases/download/{{ release.tag }}/yq_linux_amd64"
    dest: "{{ bin_dir }}/yq"
    mode: a+x
  become: true
