---
- name: Get Latest Release from GitHub
  community.general.github_release:
    action: latest_release
    user: bluetuith-org
    repo: bluetuith
  register: bluetuith_release

- name: Download and Extract
  ansible.builtin.unarchive:
    src: "https://github.com/bluetuith-org/bluetuith/releases/download/{{ bluetuith_release.tag }}/bluetuith_{{ bluetuith_release.tag[1:] }}_Linux_x86_64.tar.gz"
    dest: "{{ setup_dir }}"
    remote_src: true

- name: Install
  ansible.builtin.copy:
    src: "{{ setup_dir }}/bluetuith"
    dest: "{{ bin_dir }}/bluetuith"
    mode: a+x
  become: true
