- name: Install networking tools
  ansible.builtin.dnf:
    name:
      - net-tools
      - traceroute
      - whois
      - nmap
      - iftop
      - tcpdump
    state: present
  become: true
  tags: ["networking"]
- ansible.builtin.import_tasks: firewall.yml
  tags: ["networking", "firewall"]
- ansible.builtin.import_tasks: speedtest-cli.yml
  tags: ["networking", "speedtest"]
- ansible.builtin.import_tasks: dnsmasq.yml
  tags: ["networking", "dns"]
- ansible.builtin.import_tasks: tailscale.yml
  tags: ["networking", "tailscale"]
