- name: Install Tailscale
  ansible.builtin.command: curl -fsSL https://tailscale.com/install.sh | sh
  become: true
- name: Enable Tailscale
  ansible.builtin.systemd:
    name: tailscaled
    state: started
    enabled: true
  become: true
- name: Install Trayscale
  community.general.flatpak:
    name: dev.deedles.Trayscale
    state: present
