- name: Install NetworkManager
  ansible.builtin.package:
    name: networkmanager
    state: present

- name: Enable NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    enabled: yes
    state: started
  become: true
