---
- name: Get latest release
  community.general.github_release:
    action: latest_release
    repo: glow
    token: "{{ github_token }}"
    user: charmbracelet
  register: glow_release

- name: Install
  ansible.builtin.dnf:
    disable_gpg_check: true
    name: https://github.com/charmbracelet/glow/releases/download/{{ glow_release.tag }}/glow-{{ glow_release.tag[1:] }}-1.x86_64.rpm
    state: present
  become: true
