- ansible.builtin.dnf:
    name: golang
    state: present
  become: true
  name: Golang

- ansible.builtin.command: go get {{ item }}
  name: Golang | Install global Go tools
  with_items:
  - honnef.co/go/tools/cmd/staticcheck
  - github.com/golangci/golangci-lint/cmd/golangci-lint
