- name: Set default Gnome shortcuts
  community.general.dconf:
    key: '{{ item.key }}'
    state: present
    value: '{{ item.value }}'
  with_items:
    - key: /org/gnome/settings-daemon/plugins/media-keys/screenshot
      value: ''''''
    - key: /org/gnome/settings-daemon/plugins/media-keys/screenshot-clip
      value: ''''''
    - key: /org/gnome/settings-daemon/plugins/media-keys/area-screenshot
      value: ''''''
    - key: /org/gnome/settings-daemon/plugins/media-keys/area-screenshot-clip
      value: ''''''
    - key: /org/gnome/settings-daemon/plugins/media-keys/window-screenshot
      value: ''''''
    - key: /org/gnome/settings-daemon/plugins/media-keys/window-screenshot-clip
      value: ''''''
    - key: /org/gnome/settings-daemon/plugins/media-keys/screenreader
      value: ''''''
    - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-1
      value:
        - <Super>1
    - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-2
      value:
        - <Super>2
    - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-3
      value:
        - <Super>3
    - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-4
      value:
        - <Super>4
    - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-5
      value:
        - <Super>5
    - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-6
      value:
        - <Super>6
    - key: /org/gnome/desktop/wm/keybindings/toggle-fullscreen
      value:
        - F11
    - key: /org/gnome/desktop/wm/keybindings/show-desktop
      value:
        - <Super>D
    - key: /org/gnome/desktop/wm/keybindings/switch-input-source
      value:
        - ''
    - key: /org/gnome/desktop/wm/keybindings/switch-input-source-backwards
      value:
        - ''
    - key: /org/gnome/desktop/wm/keybindings/maximize-horizontally
      value:
        - <Super>H
    - key: /org/gnome/desktop/wm/keybindings/maximize-vertically
      value:
        - <Super>V
    - key: /org/gnome/desktop/wm/keybindings/close
      value:
        - <Super>Q
    - key: /org/gnome/desktop/wm/keybindings/activate-window-menu
      value:
        - ''
    - key: /org/gnome/desktop/wm/keybindings/move-to-center
      value:
        - <Super>C
    - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-down
      value:
        - <Super><Alt>Down
    - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-up
      value:
        - <Super><Alt>Up
    - key: /org/gnome/desktop/wm/keybindings/toggle-above
      value:
        - <Super><Alt>T
    - key: /org/gnome/desktop/wm/keybindings/switch-input-source
      value:
        - ''
- name: Set custom Gnome Shortcuts
  community.general.dconf:
    key: '{{ item.key }}'
    state: present
    value: '{{ item.value }}'
  with_items:
    - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding
      value: '''Print'''
    - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command
      value: '''flameshot gui'''
    - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name
      value: '''Print screen with flameshot'''
    - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding
      value: '''<Super>t'''
    - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command
      value: '''tilix --focus-window'''
    - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name
      value: '''Open Terminal Window'''
    - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding
      value: '''<Super>e'''
    - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command
      value: '''flatpak run it.mijorus.smile'''
    - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name
      value: '''Open Emoji Picker'''
- name: Set Custom Shortcuts List
  community.general.dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings
    value: '[''/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/'',
      ''/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/'']'
