- name: Settings | Gnome terminal
  community.general.dconf:
    key: '{{ item.key }}'
    state: present
    value: '{{ item.value }}'
  with_items:
    - key: /org/gnome/terminal/legacy/theme-variant
      value: '''dark'''
    - key: /org/gnome/terminal/legacy/new-terminal-mode
      value: '''tab'''
    - key: /org/gnome/terminal/legacy/menu-accelerator-enabled
      value: 'false'
    - key: /org/gnome/terminal/legacy/theme-variant
      value: '''dark'''
    - key: /org/gnome/terminal/legacy/new-terminal-mode
      value: '''tab'''
    - key: /org/gnome/terminal/legacy/menu-accelerator-enabled
      value: 'false'
