---
- name: Get latest release
  community.general.github_release:
    action: latest_release
    user: karol-broda
    repo: snitch
    token: "{{ github_token }}"
  register: snitch_release

- name: Download
  ansible.builtin.unarchive:
    src: "https://github.com/karol-broda/snitch/releases/download/{{ snitch_release.tag }}/snitch_{{ snitch_release.tag[1:] }}_linux_amd64.tar.gz"
    dest: "{{ setup_dir }}"
    remote_src: true
  become: true

- name: Install
  ansible.builtin.copy:
    src: "{{ setup_dir }}/snitch"
    dest: "{{ bin_dir }}/snitch"
    mode: a+x
  become: true
