---
- name: Python | Install Core PIP packages
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: "{{ python_pip_executable }}"
  loop: "{{ python_pip_packages }}"

- name: Install Uv for managing of Python envrionments
  community.general.pipx:
    name: uv
    state: present
