- name: Helm | Get release
  community.general.github_release:
    user: helm
    repo: helm
    action: latest_release
    token: "{{ github_token }}"
  register: helm_release
- name: Helm | Create tmp dir
  ansible.builtin.file:
    path: "{{ setup_dir }}/helm"
    state: directory
    mode: "0755"
- name: Helm | Download Archive
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-{{ helm_release.tag} }-linux-amd64.tar.gz"
    remote_src: true
    dest: "{{ setup_dir }}/helm"
- name: Helm | Install
  ansible.builtin.copy:
    src: "{{ setup_dir }}/helm/linux-amd64/helm"
    dest: "{{ bin_dir }}"
    mode: a+x
  become: true
- name: Helm | Install helm-secrets plugin
  ansible.builtin.command: helm plugin install https://github.com/futuresimple/helm-secrets
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/helm/plugins/helm-secrets"
- name: Helm | Install autocomplete
  ansible.builtin.shell: helm completion zsh > {{ shell_completions_dir }}/_helm
- name: Helm | Add stable repo
  ansible.builtin.command: helm repo add stable https://kubernetes-charts.storage.googleapis.com
- name: Helm | Add bitnani repo
  ansible.builtin.command: helm repo add bitnami https://charts.bitnami.com/bitnami
- name: Helm | Add fluxcd repo
  ansible.builtin.command: helm repo add fluxcd https://charts.fluxcd.io
- name: Helm | Update repos
  ansible.builtin.command: helm repo update # noqa no-changed-when
