- name: Kubectx | Get latest release
  community.general.github_release:
    user: ahmetb
    repo: kubectx
    action: latest_release
    token: "{{ github_token }}"
  register: kubectx_release
- name: Kubectx | Create tmp dir
  ansible.builtin.file:
    path: "{{ setup_dir }}/kubectx"
    state: directory
    mode: "0755"
- name: Kubectx | Download tarball
  ansible.builtin.unarchive:
    src: https://github.com/ahmetb/kubectx/archive/{{ kubectx_release.tag }}.tar.gz
    remote_src: true
    extra_opts: [--strip-components=1]
    dest: "{{ setup_dir }}/kubectx"
- name: Kubectx | Install
  ansible.builtin.copy:
    src: "{{ setup_dir }}/kubectx/kubectx"
    dest: "{{ bin_dir }}/kubectx"
    mode: a+x
  become: true
- name: Kubectx | Install Kubens
  ansible.builtin.copy:
    src: "{{ setup_dir }}/kubectx/kubens"
    dest: "{{ bin_dir }}/kubens"
    mode: a+x
  become: true
