- name: Kubeconform | Get latest release
  community.general.github_release:
    user: yannh
    repo: kubeconform
    action: latest_release
    token: "{{ github_token }}"
  register: release
- name: Kubeconform | Download Archive
  ansible.builtin.unarchive:
    src: "https://github.com/yannh/kubeconform/releases/download/{{ release.tag }}/kubeconform-linux-amd64.tar.gz"
    remote_src: true
    dest: "{{ setup_dir }}"
  become: true
