- name: Kubectl | Add Repository
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
  become: true
- name: Kubectl | Install
  ansible.builtin.dnf:
    name: kubectl
  become: true
- name: Kubectl | Install autocomplete
  ansible.builtin.shell: kubectl completion zsh > {{ shell_completions_dir }}/_kubectl
