---
- name: Install NVIDIA Drivers
  ansible.builtin.package:
    name:
      - nvidia-open
      - nvidia-prime
      - nvidia-settings
  become: true

- name: Blacklist the nouveau driver module
  community.general.kernel_blacklist:
    name: nouveau
    state: present
  become: true

- name: Update boot entries with nvidia kernel parameters
  ansible.builtin.shell: |
    for entry in /boot/loader/entries/*.conf; do
      if ! grep -q "nvidia_drm.mode=1" "$entry"; then
        sed -i 's/options /options nvidia_drm.mode=1 /' "$entry"
      fi
    done
  become: true
  changed_when: true
