---
- name: Get latest release
  community.general.github_release:
    action: latest_release
    user: Lifailon
    repo: lazyjournal
    token: "{{ github_token }}"
  register: lazyjournal_release

- name: Download
  ansible.builtin.get_url:
    url: "https://github.com/Lifailon/lazyjournal/releases/download/{{ lazyjournal_release.tag }}/lazyjournal-{{ lazyjournal_release.tag }}-linux-amd64"
    dest: "{{ bin_dir }}/lazyjournal"
    mode: a+x
  become: true
