- ansible.builtin.import_tasks: fonts.yml
- name: Desktop Control tools
  ansible.builtin.dnf:
    name:
      - python3-psutil
      - gnome-tweak-tool
      - wmctrl
      - dconf-editor
    state: present
  become: true

- name: Copy wallpaper file
  ansible.builtin.copy:
    src: wallpaper.jpg
    dest: "{{ ansible_env.HOME }}/.wallpaper.jpg"
    mode: "0644"
- name: Set Wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file://{{ ansible_env.HOME }}/.wallpaper.jpg'"
- name: Set Wallpaper position
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
- name: Set Lock screen wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "'file://{{ ansible_env.HOME }}/.wallpaper.jpg'"
- ansible.builtin.import_tasks: gnome-extensions.yml
  tags: ["gnome-extensions"]
- ansible.builtin.import_tasks: settings/gedit.yml
- ansible.builtin.import_tasks: settings/nautilus.yml
- ansible.builtin.import_tasks: settings/desktop.yml
  tags: ["settings-desktop"]
- ansible.builtin.import_tasks: settings/shell.yml
- ansible.builtin.import_tasks: settings/shortcuts.yml
  tags: ["shortcuts"]
- ansible.builtin.import_tasks: settings/terminal.yml
- ansible.builtin.import_tasks: settings/wm.yml
- ansible.builtin.import_tasks: theme.yml
- ansible.builtin.import_tasks: autostart.yml
- ansible.builtin.import_tasks: gnome-extensions-manager.yml
  tags: ["gnome-extensions-manager"]
- name: Remove Pre-installed software
  ansible.builtin.dnf:
    name:
      - rhytmbox
      - cheese
      - totem
    state: absent
  become: true
