- name: Install Font Downloader
  community.general.flatpak:
    name: org.gustavoperedo.FontDownloader
    state: present
- name: Ensure Local Fonts folder exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory
    mode: "0755"
- name: Copy Fonts
  ansible.builtin.copy:
    src: fonts
    dest: "{{ ansible_env.HOME }}/.local/share"
    mode: "0755"
- name: Install fonts packages
  ansible.builtin.dnf:
    name:
      - jetbrains-mono-fonts
      - fira-code-fonts
    state: present
  become: true
