- name: Add Folder Color copr
  ansible.builtin.command: dnf copr enable -y kleong/folder-color
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:kleong:folder-color.repo
  become: true

- name: Install Themes
  ansible.builtin.dnf:
    name:
      - papirus-icon-theme
      - folder-color-common
      - folder-color-nautilus
      - adwaita-qt4
      - adwaita-qt5
    state: present
  become: true

- name: Enable Icon theme
  community.general.dconf.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Papirus-Dark'"
- name: Copy Icons
  ansible.builtin.copy:
    src: icons
    dest: "{{ ansible_env.HOME }}/.local/share"
    mode: "0755"
