- name: Brave | Add Repository
  ansible.builtin.yum_repository:
    name: brave
    description: Brave Browser
    baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/
    gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
  become: true
- name: Brave Browser | Install
  ansible.builtin.dnf:
    name: brave-browser
  become: true
