---
- name: Install
  ansible.builtin.package:
    name:
      - zsh
      - util-linux-user
    state: present
  become: true

- name: Set as default shell
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
  become: true
