- name: Restic
  ansible.builtin.dnf:
    name: restic
    state: present
  become: true
- name: Restic | Ensure systemd directory exists
  ansible.builtin.file:
    mode: '0755'
    path: '{{ ansible_env.HOME }}/.config/systemd/user'
    state: directory
- name: Restic | Install Systemd units
  ansible.builtin.copy:
    dest: '{{ ansible_env.HOME }}/.config/systemd/user'
    mode: '0644'
    src: '{{ item }}'
  loop:
    - restic-r2-backup.service
    - restic-r2-backup.timer
    - restic-r2-prune.service
    - restic-r2-prune.timer
    - restic-nas-backup.service
    - restic-nas-backup.timer
    - restic-nas-prune.service
    - restic-nas-prune.timer
- name: Restic | Enable Restic Backup timer for B2
  ansible.builtin.systemd:
    enabled: 'no'
    name: restic-b2-backup.timer
    scope: user
- name: Restic | Enable Restic Prune timer for B2
  ansible.builtin.systemd:
    enabled: 'no'
    name: restic-b2-prune.timer
    scope: user
- name: Restic | Enable Restic Backup timer for NAS
  ansible.builtin.systemd:
    enabled: 'no'
    name: restic-nas-backup.timer
    scope: user
- name: Restic | Enable Restic Prune timer for NAS
  ansible.builtin.systemd:
    enabled: 'no'
    name: restic-nas-backup.timer
    scope: user
