---
- name: Vicinae | Download installer
  ansible.builtin.get_url:
    url: https://vicinae.dev/install.sh
    dest: "{{ setup_dir }}/vicinae-install.sh"
    mode: "0755"

- name: Vicinae | Install
  ansible.builtin.command:
    argv:
      - bash
      - "{{ setup_dir }}/vicinae-install.sh"
  become: true
  changed_when: true
