- name: Install required virtualization packages
  ansible.builtin.dnf:
    name:
      - bridge-utils
      - libvirt
      - virt-install
      - qemu-kvm
      - virt-top
      - libguestfs-tools
      - virt-manager
    state: present
  become: true

- name: Run libvirt as non-root user
  ansible.builtin.lineinfile:
    line: user = {{ user }}
    path: /etc/libvirt/qemu.conf
    regexp: ^user =
  become: true

- name: Run libvirt as non-root user
  ansible.builtin.lineinfile:
    line: group = {{ user }}
    path: /etc/libvirt/qemu.conf
    regexp: ^group =
  become: true

- name: Enable libvirtd service
  ansible.builtin.systemd:
    enabled: true
    name: libvirtd
    state: started
  become: true
