- name: Dive | Get latest release version
  community.general.github_release:
    user: wagoodman
    repo: dive
    action: latest_release
    token: "{{ github_token }}"
  register: dive_release

- name: "Dive | Download"
  ansible.builtin.unarchive:
    src: "https://github.com/wagoodman/dive/releases/download/{{ dive_release.tag }}/dive_{{ dive_release.tag[1:] }}_linux_amd64.tar.gz"
    remote_src: true
    dest: "{{ setup_dir }}"
  become: true

- name: "Dive | install"
  ansible.builtin.copy:
    src: "{{ setup_dir }}/dive"
    dest: "{{ bin_dir }}/dive"
    mode: "a+x"
  become: true
