- name: Docker | Install Repo
  ansible.builtin.yum_repository:
    name: docker
    description: Docker
    baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
    gpgkey: https://download.docker.com/linux/fedora/gpg

- name: Docker | Install Packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  become: true

- name: Docker | Add current user to Docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: true
  become: true

- name: Docker | Reload group
  ansible.builtin.command: newgrp docker
  become: true

- name: Docker | Copy Daemon.json
  ansible.builtin.copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
    mode: "0644"
  become: true

- name: Docker | Start service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
