- name: Disable firewalld
  ansible.builtin.systemd:
    enabled: false
    name: firewalld
    state: stopped
  become: true

- name: Install ufw
  ansible.builtin.dnf:
    name: ufw
  become: true

- name: Enable ufw
  ansible.builtin.systemd:
    enabled: true
    name: ufw
    state: started
  become: true

- name: Allow TCP access for GSConnect
  become: true
  community.general.ufw:
    port: 1714:1764
    proto: tcp
    rule: allow
    src: 172.17.0.1/24

- name: Allow UDP access for GSConnect
  become: true
  community.general.ufw:
    port: 1714:1764
    proto: udp
    rule: allow
    src: 192.168.1.0/24

- name: Allow access from Docker containers to the host
  become: true
  community.general.ufw:
    rule: allow
    src: 172.17.0.1/24
