---
- name: Get latest release
  community.general.github_release:
    action: latest_release
    user: beekeeper-studio
    repo: beekeeper-studio
    token: "{{ github_token }}"
  register: beekeeperstudio_release

- name: Install
  ansible.builtin.dnf:
    disable_gpg_check: true
    name: https://github.com/beekeeper-studio/beekeeper-studio/releases/download/{{ beekeeperstudio_release.tag }}/beekeeper-studio-{{ beekeeperstudio_release.tag[1:] }}.x86_64.rpm
    state: present
  become: true
