[laptops]
tuxedo-laptop ansible_connection=local ansible_python_interpreter=/usr/bin/python3
zenbook-laptop ansible_connection=local ansible_python_interpreter=/home/bruno/Code/my-linux-setup/venv/bin/python
