- name: Get latest release
  community.general.github_release:
    action: latest_release
    user: jr-k
    repo: d4s
    token: "{{ github_token }}"
  register: d4s_release

- name: Download
  ansible.builtin.unarchive:
    dest: "{{ setup_dir }}"
    src: https://github.com/jr-k/d4s/releases/download/{{ d4s_release.tag }}/d4s_{{ d4s_release.tag[1:] }}_linux_amd64.tar.gz
    remote_src: true
    mode: "0644"

- name: Install
  ansible.builtin.copy:
    src: "{{ setup_dir }}/d4s"
    dest: "{{ bin_dir }}/d4s"
    mode: a+x
  become: true
