---
- name: LayerX | Get latest release
  community.general.github_release:
    action: latest_release
    user: deveshctl
    repo: layerx
    token: "{{ github_token }}"
  register: layerx_release

- name: LayerX | Install
  ansible.builtin.dnf:
    name: https://github.com/deveshctl/layerx/releases/download/{{ layerx_release.tag }}/layerx_linux_amd64.rpm
    state: present
    disable_gpg_check: true
  become: true
