- name: Pulumi | Ensure bin dir exists
  ansible.builtin.file:
    mode: '0755'
    path: '{{ ansible_env.HOME }}/.pulumi/bin'
    state: directory
- name: Pulumi | Get latest release version
  community.general.github_release:
    action: latest_release
    repo: pulumi
    token: '{{ github_token }}'
    user: pulumi
  register: pulumi_release
- name: Pulimi | Install
  ansible.builtin.unarchive:
    dest: '{{ ansible_env.HOME }}/.pulumi/bin'
    extra_opts:
      - --strip-components=1
    mode: a+x
    remote_src: true
    src: https://get.pulumi.com/releases/sdk/pulumi-{{ pulumi_release.tag }}-linux-x64.tar.gz
