- name: Kubeconform | Get latest release
  community.general.github_release:
    action: latest_release
    repo: kubeconform
    token: '{{ github_token }}'
    user: yannh
  register: release
- name: Kubeconform | Download Archive
  ansible.builtin.unarchive:
    dest: '{{ setup_dir }}'
    remote_src: true
    src: https://github.com/yannh/kubeconform/releases/download/{{ release.tag }}/kubeconform-linux-amd64.tar.gz
  become: true
