- name: Add Copr Repository
  ansible.builtin.command:
    cmd: dnf copr enable -y erikreider/SwayNotificationCenter

- name: Install
  ansible.builtin.package:
    name:
      - swaync
    state: present
  become: true
