- name: Portmaster | Install
  ansible.builtin.dnf:
    name: https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.rpm
    state: present
    disable_gpg_check: true
  become: true
