# =======================
# Languages and runtimes
# =======================
- ansible.builtin.import_tasks: python.yml
  tags: ["python"]
- ansible.builtin.import_tasks: ruby.yml
  tags: ["ruby"]
- ansible.builtin.import_tasks: php.yml
  tags: ["php"]
- ansible.builtin.import_tasks: node.yml
  tags: ["node"]
- ansible.builtin.import_tasks: golang.yml
  tags: ["golang"]
- ansible.builtin.import_tasks: java.yml
  tags: ["java"]
- ansible.builtin.import_tasks: rust.yml
  tags: ["rust"]
# =======================
# Tools
# =======================
- ansible.builtin.import_tasks: vim.yml
  tags: ["vim"]
- ansible.builtin.import_tasks: vscode.yml
  tags: ["vscode"]
- ansible.builtin.import_tasks: postman.yml
  tags: ["postman"]
- ansible.builtin.import_tasks: meld.yml
  tags: ["meld"]
- ansible.builtin.import_tasks: gitkraken.yml
  tags: ["gitkraken"]
- ansible.builtin.import_tasks: wildcard.yml
  tags: ["wildcard"]
- ansible.builtin.import_tasks: dbeaver.yml
  tags: ["dbeaver"]
- ansible.builtin.import_tasks: hugo.yml
  tags: ["hugo"]
- ansible.builtin.import_tasks: jetbrains-toolbox.yml
  tags: ["jetbrains"]
# ===================
# Docker
# ===================
- ansible.builtin.import_tasks: docker/docker.yml
  tags: ["docker"]
- ansible.builtin.import_tasks: docker/ctop.yml
  tags: ["docker", "ctop", "github"]
- ansible.builtin.import_tasks: docker/lazydocker.yml
  tags: ["docker", "lazydocker", "github"]
- ansible.builtin.import_tasks: docker/dive.yml
  tags: ["docker", "dive", "github"]
- ansible.builtin.import_tasks: sops.yml
  tags: ["sops", "github"]
# # ============================
# # Kubernetes
# # ============================
- ansible.builtin.import_tasks: kubernetes/minikube.yml
  tags: ["minikube"]
- ansible.builtin.import_tasks: kubernetes/kubectl.yml
  tags: ["kubernetes", "kubectl"]
- ansible.builtin.import_tasks: kubernetes/kubectx.yml
  tags: ["kubernetes", "kubectx", "github"]
- ansible.builtin.import_tasks: kubernetes/helm.yml
  tags: ["kubernetes", "helm"]
- ansible.builtin.import_tasks: kubernetes/kail.yml
  tags: ["kubernetes", "kail", "github"]
- ansible.builtin.import_tasks: kubernetes/kubeconform.yml
  tags: ["kubernetes", "kubeconform", "github"]
- ansible.builtin.import_tasks: kubernetes/k9s.yml
  tags: ["kubernetes", "k9s", "github"]
- ansible.builtin.import_tasks: kubernetes/kind.yml
  tags: ["kubernetes", "kind", "github"]
- ansible.builtin.import_tasks: kubernetes/lens.yml
  tags: ["kubernetes", "lens"]
# ===================
# Cloud tools
# ===================
- ansible.builtin.import_tasks: cloud/awscli.yml
  tags: ["awscli"]
- ansible.builtin.import_tasks: cloud/doctl.yml
  tags: ["doctl", "github"]
- ansible.builtin.import_tasks: cloud/gcloud.yml
  tags: ["gcloud"]
- ansible.builtin.import_tasks: cloud/hcloud.yml
  tags: ["hcloud"]
# ===================
# Other
# ===================
- ansible.builtin.import_tasks: mkcert.yml
  tags: ["mkcert", "github"]
- ansible.builtin.import_tasks: dbcli.yml
- ansible.builtin.import_tasks: tldr.yml
  tags: ["tldr"]
- ansible.builtin.import_tasks: git-tools.yml
  tags: ["github"]
- ansible.builtin.import_tasks: terraform.yml
  tags: ["terraform", "github"]
- ansible.builtin.import_tasks: sqllitebrowser.yml
- ansible.builtin.import_tasks: pulumi.yml
  tags: ["pulumi", "github"]
- ansible.builtin.import_tasks: spotlight-studio.yml
  tags: ["spotlight-studio"]
- ansible.builtin.import_tasks: gh-cli.yml
  tags: ["gh-cli", "github"]
- ansible.builtin.import_tasks: glab-cli.yml
  tags: ["glab-cli", "gitlab"]
- ansible.builtin.import_tasks: flux.yml
  tags: ["fluxcd", "github"]
- ansible.builtin.import_tasks: goreleaser.yml
  tags: ["goreleaser", "github"]
- ansible.builtin.import_tasks: direnv.yml
  tags: ["direnv"]
- ansible.builtin.import_tasks: lefthook.yml
  tags: ["go", "lefthook"]
- ansible.builtin.import_tasks: github-desktop.yml
  tags: ["github-desktop"]
- ansible.builtin.import_tasks: mongodb.yml
  tags: [mongodb]
- ansible.builtin.import_tasks: redis.yml
  tags: [redis]
- ansible.builtin.import_tasks: copier.yml
  tags: [copier]
- ansible.builtin.import_tasks: watchexec.yml
  tags: [watchexec]
- ansible.builtin.import_tasks: nix.yml
  tags: [nix]
- ansible.builtin.import_tasks: scriptkit.yml
  tags: [scriptkit]
- ansible.builtin.import_tasks: hostctl.yml
  tags: [hostctl]
- ansible.builtin.import_tasks: insomnia.yml
  tags: ["insomnia"]
- ansible.builtin.import_tasks: dev-toolbox.yml
  tags: ["dev-toolbox"]
