- name: "GitHub CLI | Get Latest release"
  community.general.github_release:
    user: cli
    repo: cli
    action: latest_release
    token: "{{ github_token }}"
  register: release
- name: "GitHub CLI | Install"
  ansible.builtin.dnf:
    name: "https://github.com/cli/cli/releases/download/{{ release.tag }}/gh_{{ release.tag[1:] }}_linux_amd64.rpm"
    state: present
  become: true
