- name: Jetbrains Toolbox
  ansible.builtin.unarchive:
    src: https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz
    remote_src: true
    dest: "{{ bin_dir }}"
    extra_opts: [--strip-components=1]
    mode: a+x
  become: true
- name: Jetbrains Toolbox | Install Desktop file
  ansible.builtin.copy:
    src: applications/jetbrains-toolbox.desktop
    dest: "{{ applications_dir }}/jetbrains-toolbox.desktop"
    mode: "0644"
