- name: Mkcert | Get latest release
  community.general.github_release:
    user: FiloSottile
    repo: mkcert
    action: latest_release
    token: "{{ github_token }}"
  register: release
- name: Mkcert | Install Binary
  ansible.builtin.get_url:
    url: "https://github.com/FiloSottile/mkcert/releases/download/{{ release.tag }}/mkcert-{{ release.tag }}-linux-amd64"
    dest: "{{ bin_dir }}/mkcert"
    mode: a+x
  become: true
- name: Mkcert | Install certificates
  ansible.builtin.command: mkcert -install
