- name: Installs NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: present
  become: true
- name: Installs Global NPM Packages
  community.general.npm:
    name: "{{ item }}"
    global: true
  with_items:
    - "@nestjs/cli"
    - "@vue/cli"
    - "add-gitignore"
    - "artillery"
    - "caniuse-cmd"
    - "carbon-now-cli"
    - "cloudinary-cli"
    - "commitizen"
    - "conduct"
    - "conventional-changelog-cli"
    - "nuxi"
    - "electron"
    - "fast-cli"
    - "firebase-tools"
    - "fkill-cli"
    - "fx"
    - "gatsby-cli"
    - "get-port-cli"
    - "localtunnel"
    - "hasha-cli"
    - "mdless"
    - "mermaid.cli"
    - "mklicense"
    - "nativefier"
    - "nativescript"
    - "netlify-cli"
    - "pageres-cli"
    - "readme-md-generator"
    - "@brpaz/sao-reloaded"
    - "serve"
    - "svgo"
    - "serverless"
    - "sitespeed.io"
    - "svg-term-cli"
    - "tablemark-cli"
    - "trash-cli"
    - "typescript"
    - "vuepress"
    - "weallcontribute"
    - "yarn"
    - "plop"
    - "vercel"
    - "@cloudflare/wrangler"
- name: FNM | Get latest release version
  community.general.github_release:
    user: bitwarden
    repo: cli
    action: latest_release
    token: "{{ github_token }}"
  register: fnm_release
- name: FNM | Install
  ansible.builtin.unarchive:
    remote_src: true
    src: https://github.com/Schniz/fnm/releases/download/{{ fnm_release.tag }}/fnm-linux.zip
    dest: "{{ bin_dir }}"
    mode: a+x
  become: true
