- name: Pulumi | Ensure bin dir exists
  file:
    path: "{{ ansible_env.HOME }}/.pulumi/bin"
    state: directory
    mode: 0755

- name: Pulumi | Get latest release version
  github_release:
    user: pulumi
    repo: pulumi
    action: latest_release
    token: "{{ github_token }}"
  register: pulumi_release

- name: Pulimi | Install
  unarchive:
    src: https://get.pulumi.com/releases/sdk/pulumi-{{ pulumi_release.tag}}-linux-x64.tar.gz
    remote_src: true
    extra_opts: [--strip-components=1]
    mode: a+x
    dest: "{{ ansible_env.HOME }}/.pulumi/bin"
