- name: ScriptKit | Get latest release
  community.general.github_release:
    user: johnlindquist
    repo: kitapp
    action: latest_release
    token: "{{ github_token }}"
  register: kit_release
- name: ScriptKit | Download AppImage
  ansible.builtin.get_url:
    url: "https://github.com/johnlindquist/kitapp/releases/download/{{ kit_release.tag }}//Kit-Linux-{{ kit_release.tag[1:] }}-x86_64.AppImage"
    dest: "/opt/ScriptKit.AppImage"
    mode: a+x
  become: true
- name: ScriptKit | Install Desktop file
  ansible.builtin.copy:
    src: applications/scriptkit.desktop
    dest: "{{ applications_dir }}/scriptkit.desktop"
    mode: "0644"
