- name: Spotlight Studio | Download AppImage
  ansible.builtin.get_url:
    url: "https://github.com/stoplightio/studio/releases/latest/download/stoplight-studio-linux-x86_64.AppImage"
    dest: "/opt/Spotlight-Studio.AppImage"
    mode: a+x
  become: true
- name: Spotlight Studio | Install Desktop file
  ansible.builtin.copy:
    src: applications/spotlight-studio.desktop
    dest: "{{ applications_dir }}/spotlight-studio.desktop"
    mode: "0644"
