- name: Terraform | Get Latest version
  community.general.github_release:
    user: hashicorp
    repo: terraform
    action: latest_release
    token: "{{ github_token }}"
  register: release
- name: "Terraform | Download and install"
  ansible.builtin.unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ release.tag[1:] }}/terraform_{{ release.tag[1:] }}_linux_amd64.zip"
    remote_src: true
    dest: "{{ bin_dir }}"
    mode: u+rwx
  become: true
