- name: Tldr | Get client latest release
  community.general.github_release:
    user: isacikgoz
    repo: tldr
    action: latest_release
  register: release
- name: Tldr | Install command line client
  ansible.builtin.unarchive:
    src: "https://github.com/isacikgoz/tldr/releases/download/{{ release.tag }}/tldr_{{ release.tag[1:] }}_linux_amd64.tar.gz"
    remote_src: true
    dest: "{{ setup_dir }}"
- name: Tldr | Install
  ansible.builtin.copy:
    src: "{{ setup_dir }}/tldr"
    dest: "{{ bin_dir }}"
    mode: a+x
  become: true
- name: Tldr | Update pages
  ansible.builtin.command: tldr -u # noqa no-changed-when
