- name: VS Code | Add Repository
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  become: true
- name: VS Code | Install
  ansible.builtin.dnf:
    name: code
  become: true
- name: VS Code | Install Sync Settings Extension
  ansible.builtin.command: code --install-extension Shan.code-settings-sync
