- name: WebCatalog | Get latest release
  community.general.github_release:
    action: latest_release
    repo: webcatalog-app
    token: "{{ github_token }}"
    user: webcatalog
  register: wc_release

- name: WebCatalog | Download AppImage
  ansible.builtin.get_url:
    dest: /opt/WebCatalog.AppImage
    url:
      https://github.com/webcatalog/webcatalog-app/releases/download/{{ wc_release.tag
      }}/WebCatalog-{{ wc_release.tag[1:] }}.AppImage
    mode: a+x
  become: true

- name: WebCatalog | Install Desktop file
  ansible.builtin.copy:
    src: webcatalog.desktop
    dest: "{{ applications_dir }}/webcatalog.desktop"
    mode: "0644"

