---
- name: Install
  community.general.github_release:
    action: latest_release
    user: Satty-org
    repo: Satty
    token: "{{ github_token }}"
  register: satty_release

- name: Download
  ansible.builtin.unarchive:
    src: "https://github.com/Satty-org/Satty/releases/download/{{ satty_release.tag }}/satty-x86_64-unknown-linux-gnu.tar.gz"
    dest: "{{ setup_dir }}"
    remote_src: true
  become: true

- name: Install
  ansible.builtin.copy:
    src: "{{ setup_dir }}/satty"
    dest: "{{ bin_dir }}/satty"
    mode: a+x
  become: true
