- name: MiniDLNA | Install
  ansible.builtin.dnf:
    name: minidlna
    state: present
  become: true
- name: Set the MiniDLNA configuration file
  ansible.builtin.template:
    dest: /etc/minidlna.conf
    mode: '0644'
    src: minidlna/minidlna.conf.j2
  become: true
- name: Enable MiniDLNA Server
  ansible.builtin.systemd:
    enabled: true
    name: minidlna
    state: started
  become: true
