- ansible.builtin.command: command -v cargo
  ignore_errors: true
  name: Rust | check if cargo is installed
  register: cargo_exists
- ansible.builtin.get_url:
    dest: /tmp/sh.rustup.rs
    force: 'true'
    mode: '0755'
    url: https://sh.rustup.rs
  name: Rust | Download Installer
  when: cargo_exists is failed
- ansible.builtin.command: /tmp/sh.rustup.rs -y
  name: Rust | Install
  when: cargo_exists is failed
