---
- name: Install
  ansible.builtin.package:
    name: ydotool
    state: present
  become: true

- name: Ensure systemd override directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/ydotool.service.d
    state: directory
    mode: "0755"
    owner: root
    group: root
    recurse: true
  become: true

- name: Ensure user is part of input group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: input
    append: true
  become: true

- name: Create systemd override file
  ansible.builtin.copy:
    content: |
      [Service]
      # Create socket with permissions that allow user access
      ExecStartPost=/bin/chmod 660 /tmp/.ydotool_socket
    path: /etc/systemd/system/ydotool.service.d/override.conf
    dest: /etc/systemd/system/ydotool.service.d/override.conf
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Start Service
  ansible.builtin.systemd:
    name: ydotool.service
    state: started
    enabled: true
  become: true
