- name: Loki | Ensure Configuration folder exists
  ansible.builtin.file:
    path: /etc/loki
    state: directory
    mode: '"0755"'
  become: true
- name: Loki | Ensure Configuration file exists
  ansible.builtin.template:
    src: loki/loki-local-config.yaml.j2
    dest: /etc/loki/config.yaml
    mode: "0644"
  become: true
- name: Loki | Ensure data volume exists
  community.docker.docker_volume:
    name: loki-storage
    state: present
- name: Loki | Start container
  community.docker.docker_container:
    name: loki
    image: grafana/loki:2.8.4
    state: started
    command: -config.file=/etc/loki/config.yaml
    labels:
      traefik.enable: "false"
    networks:
      - name: monitoring
    restart_policy: "unless-stopped"
    volumes:
      - /etc/loki/config.yaml:/etc/loki/config.yaml
      - loki-storage:/loki
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
