- name: Prometheus | Ensure Prometheus data volume exists
  community.docker.docker_volume:
    name: prometheus-data
    state: present
- name: Prometheus | Ensure configuration directory exists
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '"0755"'
  become: true
- name: Prometheus | Ensure Configuration folder exists
  ansible.builtin.template:
    src: prometheus/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: "0644"
  become: true
- name: Prometheus | Start Container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:v2.46.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--storage.tsdb.retention.size=5GB'
    state: started
    restart_policy: "unless-stopped"
    networks:
      - name: monitoring
      - name: traefik-public
    volumes:
      - "prometheus-data:/prometheus"
      - "/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik-public
      traefik.http.routers.prometheus.rule: "Host(`prometheus.docker`)"
      traefik.http.routers.prometheus.entrypoints: "web"
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s
