- name: Sourcegraph | Ensure Sourcegraph data volume is present
  community.docker.docker_volume:
    name: sourcegraph_data
    state: present
- name: Sourcegraph | Create configuration directory
  ansible.builtin.file:
    path: /etc/sourcegraph
    state: directory
    mode: "0755"
  become: true
- name: Sourcegraph | Create network
  community.docker.docker_network:
    name: sourcegraph
    state: present
- name: Sourcegraph | Start Server container
  community.docker.docker_container:
    name: sourcegraph
    image: sourcegraph/server:5.1.7
    restart_policy: "unless-stopped"
    networks:
      - name: sourcegraph
      - name: traefik-public
    volumes:
      - "sourcegraph_data:/var/opt/sourcegraph sourcegraph/"
      - "/etc/sourcegraph/:/etc/sourcegraph/"
    env:
      DISABLE_OBSERVABILITY: "true"
    labels:
      traefik.enable: "true"
      traefik.http.routers.sourcegraph.rule: "Host(`sg.docker`)"
      traefik.http.routers.sourcegraph.tls: "false"
      traefik.http.routers.sourcegraph.entrypoints: "web"
      traefik.http.services.sourcegraph.loadbalancer.server.port: "7080"
- name: Sourcegraph | Start Serve git
  community.docker.docker_container:
    name: sourcegraph-serv-git
    image: sourcegraph/src-cli:5.1
    command: serve-git /data/repos
    restart_policy: "unless-stopped"
    networks:
      - name: sourcegraph
    volumes:
      - '~/Code:/data/repos'
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik-public
